### ISSUE TITLE
offset cursor

### ISSUE THREAD

**Issue by TorchedSammy** [reeflective/readline#1]
was wondering about using this library so i tested it out with my normal prompt and the cursor is slightly offset  
the reason for this is because of the delta, since using something like `%` doesnt make this

**Comment by maxlandon** [comment]
Hello Sammy,
Yes there are a few things I didn't take care of in the prompt code (among which are all emojis and fonts that can't be stripped as easily as colored strings.)
Stay in touch, I will solve that soon, along with _many_ other changes and enhancements.
All of this will land towards the end of December.
As well, watching your profile: you might be interested by github.com/lmorg/murex (the latter uses a readline lib from which I forked mine and enhanced it). Pointing this to you not for readline code, but for the entire shell itself: the maintainer has spent much time writing it.
I'll ping here as soon as problems are solved.

**Comment by TorchedSammy** [comment]
hi, any updates?

**Comment by maxlandon** [comment]
Hello Sammy, sorry for having ghosted the repo for months, I was away. So as you noticed I got back to it a few weeks ago.

The library has been completely redesigned, with a new keymap model, many new features and enhancements, and a somewhat reduced/cleaned API. So it is going to be slightly different from the one you're currently using, especially as far as completion/history/hints are declared and populated.
I hope that the new version will help you in your shell.

Related to your proposal:
- Fish-like autosuggestions have been implemented in the new version. Probably no need for this.
- I'm still in want of implementing a decent multiline editing support, in case someone other than you would want to use this readline for a shell. So there are a couple of things to consider here. First, I opened a specific issue (#4) to describe what should be done and where someone should look for correct and clean logic.
Don't get me wrong, it's not trivial to implement, so I'm just saying this in case you want to knock yourself off at it ! Anyway, and if yes, I suggest to go over the codebase first, starting by `readline.go`.
- I saw you added some emacs stuff to your fork: as well, you'll see that the new version integrates all of those... and more !

Available if you have questions or suggestions !
Hilbish looks cool by the way !

**Comment by TorchedSammy** [comment]
> Available if you have questions or suggestions

since ive finally decided to start an attempt at using this in hilbish, i have a few things to ask and say:

- how do i set the prompt from the go?
- what happened to the display types for the completions?

why is there a config for this now? i feel like this functionality could be done in some separate package, also helps me avoid the extra yaml dependency. i also think the reduced api is more of a bad thing than good.

**Comment by maxlandon** [comment]
Prompts: check https://github.com/reeflective/readline/wiki/Prompts

Display types: Disappeared. The completion API has radically changed. 

Autocomplete: because the configuration enables as-you-type autocomplete by default. I should probably set it off though.

Config: there is a configuration so that anyone can use its own bindings when the tool they are using is using readline. check https://github.com/reeflective/readline/wiki/Configuration-File
Down the road the package might be refactored, but that is not planned for now.


### Issues
- Enter: will check that. Should not happen.
- Cursor: weird, it is supposed to correctly count prompt runes. I will check that also.

**Comment by TorchedSammy** [comment]
> Prompts: check https://github.com/reeflective/readline/wiki/Prompts

the prompt type here is not public

i think it would be good to be able to set the available config values via the go api, and also adding custom widgets?

**Comment by TorchedSammy** [comment]
> I tried doing any keybind that would be expected to work (up arrow for history, Ctrl-R) and it froze up?

any suggestions for this either

**Comment by maxlandon** [comment]
> > Prompts: check https://github.com/reeflective/readline/wiki/Prompts
> 
> 
> 
> the prompt type here is not public (edit: i just made it on a fork)
> 
> 
> 
> i think it would be good to be able to set the available config values via the go api, and also adding custom widgets?

Prompt: 
```go
var shell = *readline.Instance
shell.Prompt.Primary()
...
```

Config:

```go
var shell = *readline.Instance
shell.Config.Vim.Cursor = ""
```

Existing widgets:
```go
var shell = *readline.Instance
shell.Config.Keymaps["viins"]["^B" = "backward-word"
```

Custom callbacks:
https://github.com/reeflective/readline/wiki/Custom-Callbacks

**Comment by maxlandon** [comment]
> > I tried doing any keybind that would be expected to work (up arrow for history, Ctrl-R) and it froze up?
> 
> 
> 
> any suggestions for this either

Could you give me a snippet of your code for this ? Thanks.

**Comment by TorchedSammy** [comment]
i have my code in hilbish via the pr here https://github.com/Rosettea/Hilbish/pull/228

**Comment by TorchedSammy** [comment]
ok so turns out the keybinds changed which i didnt look at, im definitely gonna set it back on hilbish because esc-everthing is what i hate on emacs.

so now that i looked at them, i have noticed that history search is very slow, it is noticeably a lot slower than the old version. and there is still the previously mentioned lock ups which seem t be because the line is empty when trying to use a bind?

**Comment by maxlandon** [comment]
Emacs escape: note that the escape notation is equivalent to the Alt key modifier.
So given an "Esc-A" key combo, it is equivalent to "Alt-A".
The difference is that if you use ESC, you use it sequentially with A, while Alt must be pressed together with A.

History search: no reason why it would be slower. The pattern matching logic did not change. Or... you have millions of lines ? Not sure what to think/say here.

Lock ups/empty line: Can you reformulate ? I don't understand what you mean here.

**Comment by TorchedSammy** [comment]
> History search: no reason why it would be slower. The pattern matching logic did not change. Or... you have millions of lines ? Not sure what to think/say here.

i have 40k lines of history

> Lock ups/empty line: Can you reformulate ? I don't understand what you mean here

if i have an empty line and try to use certain keybinds (like history backward search) it seems like the library goes into some infinite loop? or something else causes it to not accept more input

**Comment by maxlandon** [comment]
Back to this:

- History search: This is probably because by default, history search commands (when using completions) recompute regexp matching subgroups highlighting.
  This has not changed with the last version, so it should not be faster. I'll try to find a way to speed this up, so that this lag disappears.

- Lock ups/empty line: This should be solved. The library has been entirely rewritten, including key dispatch and various related stuff. Previously, there were some
  lacks in the underlying line/visual selection logic, and on top of a deficient dispatch, this would make things worse. Should be solved now.

**Comment by maxlandon** [comment]
Solved lagging history search. The logic has been enhanced and does not fetch/processes more lines than what the terminal can show. All history search submodes work perfect now.
Thanks for pointing this out !
