### ISSUE TITLE
it doesn't work on git bash in Windows

### ISSUE THREAD

**Issue by JackKCWong** [reeflective/readline#2]
What a great library! I'd love to use it in Windows. But I've tried the following combinations and only 1 of them worked:

* git bash - screen goes blank and need to ctrl+c multiple times to exit
* git bash in cmder - same as above
* git bash in Windows terminal - seems the cursor is out of place, and each key stroke prints a newline. see attached.

![image](https://user-images.githubusercontent.com/19254763/156190672-bf445c7f-8045-4af9-8260-7cab9ba084c7.png)

I'd love to help. I know enough about Go but not enough about terminals. If you can point me in the right direction, I can try to fix it. (If that's even fixable, I know Windows is notoriously bad at terminals...but that's what I am stuck with)
I am mainly interested in fixing it for git bash.

**Comment by maxlandon** [comment]
Hello ! Sorry I've been completely off for a few months, and I resumed work on this library only a few weeks ago.

The library has been almost entirely rewritten, with a new model, cleaner code base, and many new features and enhancements. If you are still using it, or considering, could you try the new version and tell me if the problem persists ?
Thanks a lot.

**Comment by JackKCWong** [comment]
Wonderful news! It's been a long time and I've switched to a Mac :)
I am still interested in testing it though, just have to find a Windows kit, maybe in 1 or 2 weeks.

**Comment by maxlandon** [comment]
Hello @JackKCWong 
Did you give this a try ?
Normally the latest release should have fixed cursor offset computations, but I would greatly appreciate a feedback for Windows !

**Comment by JackKCWong** [comment]
hey, sry I haven't found any snippet to run a quick test on it and haven't got the time to dive into the docs. 
I did try the console/example mentioned in the readme but it's pretty off. Not sure if you intend to support Windows or now. 
I will have another go next week.
![IMG_20230210_124130_edit_67006356603317](https://user-images.githubusercontent.com/19254763/218003860-6f419da3-26f9-4500-a89b-222958a6df48.jpg)

**Comment by maxlandon** [comment]
I have not personally tested for Windows.
Note that the example console uses a default Oh-my-posh prompt engine/configuration, and oh-my-posh is supposed to be working great on Windows.
So I'll try my example on a Windows machine, and will reach back to you once done, with things fixed on my side.
