### ISSUE TITLE
expose keymapMode type

### ISSUE THREAD

**Issue by TorchedSammy** [reeflective/readline#21]

**Comment by maxlandon** [comment]
The new version of the library being based on `.inputrc` configuration files and the associated bind model, there is no need anymore for an exported (or special) KeymapMode type (it has in fact disappeared, except for internal needs which don't collide with users wanting to add custom keymaps.)

Documentation on how to bind custom commands and/or custom keymaps will soon follow.
Closing this now, but I will add a link to the relevant documentation once published.
