### ISSUE TITLE
consolidating changes/fixes from hilbish's fork

### ISSUE THREAD

**Issue by TorchedSammy** [reeflective/readline#3]
hello. I see that you are back and making fixes to the readline library here. since I incorporated it into hilbish, I have found and fixed a few of the problems I've encountered in it (and added things such as fish-style hints) that I'm sure would be a good fit for upstream. if you want, I can try to update my fork to upstream changes and make a PR.

**Comment by TorchedSammy** [comment]
(you can check https://github.com/Rosettea/Hilbish) and the history in the readline package for details

**Comment by maxlandon** [comment]
Redirecting you to the first issue you opened (#1), with answers :smiley: !
