### ISSUE TITLE
'\' character consumed but not used

### ISSUE THREAD

**Issue by jay-fray** [reeflective/readline#46]
Heyo! Thanks for library!

Found an issue while playing around; The `\` character appears to be consumed in the background without actually printing/appending to the line editor.

Minimum example:
```go
package main

import (
	"fmt"
	"log"

	"github.com/reeflective/readline"
)

func main() {
	rl := readline.NewShell()

	rl.Prompt.Primary(func() string {
		return " > "
	})

	for {
		line, err := rl.Readline()
		if err != nil {
			if err.Error() == "interrupt" {
				continue
			}
			log.Fatal(err)
		}

		if len(line) == 0 {
			continue
		}

		fmt.Println(line)
	}
}
```

When I type `\`, it just goes off into the ether. The final println doesn't contain it either.

Verified that every other key, including it's shifted character (pipe/`|` on US keyboard) is working as expected.

Let me know if you need any additional info!

**Comment by jay-fray** [comment]
Just to check, I printed out all the binds:
```
Mode : emacs
        Key : \
                Is Macro : false
                Action   : self-insert
Mode : emacs-standard
        Key : \
                Is Macro : false
                Action   : self-insert
Mode : emacs-meta
        Key : \
                Is Macro : false
                Action   : delete-horizontal-space
Mode : vi-insert
        Key : \
                Is Macro : false
                Action   : self-insert
```
Would the `emacs-meta` be the problem here?

**Comment by maxlandon** [comment]
Thanks a lot for the ouput and explanations.
Looking at this at the moment.

**Comment by maxlandon** [comment]
Are you using the latest release ?

**Comment by jay-fray** [comment]
I believe so, yes:
```
module codeberg.org/distek/testthingshere

go 1.17

require github.com/reeflective/readline v1.0.4

require (
	github.com/rivo/uniseg v0.4.4 // indirect
	golang.org/x/sys v0.8.0 // indirect
	golang.org/x/term v0.8.0 // indirect
)
```

**Comment by maxlandon** [comment]
This is bizarre. (I have another issue) but not this one.
Does the backspace key works fine ?

Testing this on your program, without any `.inputrc` file loaded.
What is your system/shell/terminal, if I may ?

**Comment by jay-fray** [comment]
Actually, no! Backspace is technically working but not updating the line editor with the changes, but the final result is as expected.
System (linux):
```
└[INS]─> uname -r
6.3.4-arch1-1
```

Shell: 
```
└[INS]─> bash --version
GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

And terminal is foot: https://codeberg.org/dnkl
```
└[INS]─> foot --version
foot version: 1.14.0 +pgo +ime +graphemes -assertions
```

**Comment by maxlandon** [comment]
> Just to check, I printed out all the binds:
> 
> ```
> Mode : emacs
>         Key : \
>                 Is Macro : false
>                 Action   : self-insert
> Mode : emacs-standard
>         Key : \
>                 Is Macro : false
>                 Action   : self-insert
> Mode : emacs-meta
>         Key : \
>                 Is Macro : false
>                 Action   : delete-horizontal-space
> Mode : vi-insert
>         Key : \
>                 Is Macro : false
>                 Action   : self-insert
> ```
> 
> Would the `emacs-meta` be the problem here?

Sorry, forgot to answer to this.
No its likely not due to this, as the standard emacs and emacs-standard keyboards are the same (they are copies of each other, and `emacs-ctlx` and `emacs-meta` are subsets of the `emacs` one: `emacs is a combination of both.)

**Comment by maxlandon** [comment]
I'm facing a problem, I don't run Wayland on my machine, so I'm not able to solve this right now.
On Xterm, your program prints and returns the backslashes.

**Comment by jay-fray** [comment]
On all my terminal emulators, I get the same issue.

One moment.

**Comment by jay-fray** [comment]
My word that was rough.

So I ended up spinning up a docker container and throwing the code in there. The backslash works as expected, so it's something higher on my system that's causing the issue.

Thanks for the fast response and help!

The backspace is still not working properly, but I'm assuming you're looking into that. If not, lemme know and I can throw up another issue.

**Comment by maxlandon** [comment]
Yes backspace solved, its was a problem with clearing line. Pushing a fix and release for this.
If you end up finding the issue on your system and you deem it relevant, to hesitate to come back !

This project is rather young and not widespread/tested yet, it must be widely tested before being sure of everything (and maintainers sleeping at nights !)

**Comment by maxlandon** [comment]
Released with bug fix: https://github.com/reeflective/readline/releases/tag/v0.1.4

**Comment by jay-fray** [comment]
> Yes backspace solved, its was a problem with clearing line. Pushing a fix and release for this. If you end up finding the issue on your system and you deem it relevant, to hesitate to come back !

Will do!

> This project is rather young and not widespread/tested yet, it must be widely tested before being sure of everything (and maintainers sleeping at nights !)

I'll be testing the heck out of it: Writing my own shell for fun (and maybe prod use)! :)

**Comment by maxlandon** [comment]
> I'll be testing the heck out of it: Writing my own shell for fun (and maybe prod use)! :)

Bold but great endeavour, good luck.
